const list = [
    {   id:1214,
        name:'Private Cottage with River view, Terrace & Garden',
        des:'Root Farms, is located on the river front & is right next to York Winery. This is a standalone farm stay with a private garden , terrace, river view and located in a 3 acre farm. Enjoy the tranquility of a farmstay while also being close to popular destinations. We are 5 mins away from Sula wines and about 20 minutes from Nashik city.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-49020640/original/407eaa03-2ffe-4aed-a0d9-2e020eab6afb.jpeg?im_w=1200',
        price:2500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'kolkata WestBengal'
    },
    {   
        id:1285,
        name:'Unique Kamshet Dome w/ Plunge Pool & Scenic Views',
        des:'The white bougainvillea climbs over the cotton tree and hangs like a veil covering the sun at day and dances by night. The lily’s tucked away in the corner sing with the birds and the Jackman’s Clematis welcomes you at the front gate swaying with the wind.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-40333094/original/64153613-aebd-4960-a611-4b54e6ed4deb.jpeg?im_w=1200',
        price:2800,
        guest:6,
        bedroom:2,
        beds:5,
        bathroom:2,
        location:'Goa'
    },
    {   
        id:9614,
        name:'Forest Villa in the Hills with Tree House & a Pool',
        des:'Lush green lawns, smoky mountains, and clouds rolling down during rains, nature at its best! Take a dip in the pool or relax on the lawns, go on a trek, breathe in the pure air. Ideate, meditate – make the most of the peace and tranquility in the air. Wake up early morning to the chirping of birds. Enjoy the waterfalls in the monsoon.',
        pic:'https://a0.muscache.com/im/pictures/d602e1ba-c4e7-4980-94c4-75ba34baf339.jpg?im_w=1200',
        price:2100,
        guest:3,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Digha WestBengal'
    },
    {   
        id:10321,
        name:'Karjat, Chalet Kawaii by Leisurely Experiences',
        des:'When you need to unwind with your loved ones, jump into this chalet to experience hills, trees, and fireflies. We apologize in advance for the chirping of birds, being your alarm, and trees interfering your personal space. Remember, breathe.',
        pic:'https://a0.muscache.com/im/pictures/f6641879-8e6f-410d-a7e8-a4a0a4366bf0.jpg?im_w=1200',
        price:12200,
        guest:8,
        bedroom:3,
        beds:6,
        bathroom:3,
        location:'Golden Beach Pondi'
    },
    {
        id:129674,
        name:'1 BHK AC Chalets, Karjat',
        des:'The resort is located in Karjat near Mumbai, is the perfect getaway to create memorable moments with your family. It offers you an opportunity to invest in fully furnished weekend homes that are carefully planned to let you and your family enjoy your weekends in a resort atmosphere, at a home away from home amidst greenery, tranquility and various amenities.',
        pic:'https://a0.muscache.com/im/pictures/f15cc2bf-6877-4901-9d91-a63b318aed34.jpg?im_w=1200',
        price:15000,
        guest:6,
        bedroom:2,
        beds:4,
        bathroom:2,
        location:'Kerala'
    },
    {   id:152301,
        name:'Amreena Farmhouse - Stay-Lunch-Dinner-Brkfst.',
        des:'PRICE IS PER PERSON PER NIGHT including breakfast lunch dinner with Veg and non veg food.  Amreena Farmhouse, the highest rated farmhouse on airbnb, is a beautiful space, just 2 to 2.5 hours away from Mumbai. Its in a place called Avalas which is 7 kms from Karjat and 3kms from Raddison hotel. ',
        pic:'https://a0.muscache.com/im/pictures/60dcd026-419d-4a06-a096-f5b676c8bda6.jpg?im_w=1200',
        price:6500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Darjelling WestBengal'
    },
    {
        id:1214742,
        name:'Private Cottage with River view, Terrace & Garden',
        des:'Root Farms, is located on the river front & is right next to York Winery. This is a standalone farm stay with a private garden , terrace, river view and located in a 3 acre farm. Enjoy the tranquility of a farmstay while also being close to popular destinations. We are 5 mins away from Sula wines and about 20 minutes from Nashik city.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-49020640/original/407eaa03-2ffe-4aed-a0d9-2e020eab6afb.jpeg?im_w=1200',
        price:2500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'kolkata WestBengal'
    },
    {   
        id:96741,
        name:'Unique Kamshet Dome w/ Plunge Pool & Scenic Views',
        des:'The white bougainvillea climbs over the cotton tree and hangs like a veil covering the sun at day and dances by night. The lily’s tucked away in the corner sing with the birds and the Jackman’s Clematis welcomes you at the front gate swaying with the wind.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-40333094/original/64153613-aebd-4960-a611-4b54e6ed4deb.jpeg?im_w=1200',
        price:2800,
        guest:6,
        bedroom:2,
        beds:5,
        bathroom:2,
        location:'Goa'
    },
    {
        id:1249814,
        name:'Forest Villa in the Hills with Tree House & a Pool',
        des:'Lush green lawns, smoky mountains, and clouds rolling down during rains, nature at its best! Take a dip in the pool or relax on the lawns, go on a trek, breathe in the pure air. Ideate, meditate – make the most of the peace and tranquility in the air. Wake up early morning to the chirping of birds. Enjoy the waterfalls in the monsoon.',
        pic:'https://a0.muscache.com/im/pictures/d602e1ba-c4e7-4980-94c4-75ba34baf339.jpg?im_w=1200',
        price:2100,
        guest:3,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Digha WestBengal'
    },
    {
        id:632541,
        name:'Karjat, Chalet Kawaii by Leisurely Experiences',
        des:'When you need to unwind with your loved ones, jump into this chalet to experience hills, trees, and fireflies. We apologize in advance for the chirping of birds, being your alarm, and trees interfering your personal space. Remember, breathe.',
        pic:'https://a0.muscache.com/im/pictures/f6641879-8e6f-410d-a7e8-a4a0a4366bf0.jpg?im_w=1200',
        price:12200,
        guest:8,
        bedroom:3,
        beds:6,
        bathroom:3,
        location:'Golden Beach Pondi'
    },
    {
        id:1967412,
        name:'1 BHK AC Chalets, Karjat',
        des:'The resort is located in Karjat near Mumbai, is the perfect getaway to create memorable moments with your family. It offers you an opportunity to invest in fully furnished weekend homes that are carefully planned to let you and your family enjoy your weekends in a resort atmosphere, at a home away from home amidst greenery, tranquility and various amenities.',
        pic:'https://a0.muscache.com/im/pictures/f15cc2bf-6877-4901-9d91-a63b318aed34.jpg?im_w=1200',
        price:15000,
        guest:6,
        bedroom:2,
        beds:4,
        bathroom:2,
        location:'Kerala'
    },
    {
        id:1452487,
        name:'Amreena Farmhouse - Stay-Lunch-Dinner-Brkfst.',
        des:'PRICE IS PER PERSON PER NIGHT including breakfast lunch dinner with Veg and non veg food.  Amreena Farmhouse, the highest rated farmhouse on airbnb, is a beautiful space, just 2 to 2.5 hours away from Mumbai. Its in a place called Avalas which is 7 kms from Karjat and 3kms from Raddison hotel. ',
        pic:'https://a0.muscache.com/im/pictures/60dcd026-419d-4a06-a096-f5b676c8bda6.jpg?im_w=1200',
        price:6500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Darjelling WestBengal'
    },
    {
        id:12188564,
        name:'Private Cottage with River view, Terrace & Garden',
        des:'Root Farms, is located on the river front & is right next to York Winery. This is a standalone farm stay with a private garden , terrace, river view and located in a 3 acre farm. Enjoy the tranquility of a farmstay while also being close to popular destinations. We are 5 mins away from Sula wines and about 20 minutes from Nashik city.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-49020640/original/407eaa03-2ffe-4aed-a0d9-2e020eab6afb.jpeg?im_w=1200',
        price:2500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'kolkata WestBengal'
    },
    {
        id:19674124,
        name:'Unique Kamshet Dome w/ Plunge Pool & Scenic Views',
        des:'The white bougainvillea climbs over the cotton tree and hangs like a veil covering the sun at day and dances by night. The lily’s tucked away in the corner sing with the birds and the Jackman’s Clematis welcomes you at the front gate swaying with the wind.',
        pic:'https://a0.muscache.com/im/pictures/miso/Hosting-40333094/original/64153613-aebd-4960-a611-4b54e6ed4deb.jpeg?im_w=1200',
        price:2800,
        guest:6,
        bedroom:2,
        beds:5,
        bathroom:2,
        location:'Goa'
    },
    {
        id:121136544,
        name:'Forest Villa in the Hills with Tree House & a Pool',
        des:'Lush green lawns, smoky mountains, and clouds rolling down during rains, nature at its best! Take a dip in the pool or relax on the lawns, go on a trek, breathe in the pure air. Ideate, meditate – make the most of the peace and tranquility in the air. Wake up early morning to the chirping of birds. Enjoy the waterfalls in the monsoon.',
        pic:'https://a0.muscache.com/im/pictures/d602e1ba-c4e7-4980-94c4-75ba34baf339.jpg?im_w=1200',
        price:2100,
        guest:3,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Digha WestBengal'
    },
    {
        id:121778124,
        name:'Karjat, Chalet Kawaii by Leisurely Experiences',
        des:'When you need to unwind with your loved ones, jump into this chalet to experience hills, trees, and fireflies. We apologize in advance for the chirping of birds, being your alarm, and trees interfering your personal space. Remember, breathe.',
        pic:'https://a0.muscache.com/im/pictures/f6641879-8e6f-410d-a7e8-a4a0a4366bf0.jpg?im_w=1200',
        price:12200,
        guest:8,
        bedroom:3,
        beds:6,
        bathroom:3,
        location:'Golden Beach Pondi'
    },
    {
        id:1202114,
        name:'1 BHK AC Chalets, Karjat',
        des:'The resort is located in Karjat near Mumbai, is the perfect getaway to create memorable moments with your family. It offers you an opportunity to invest in fully furnished weekend homes that are carefully planned to let you and your family enjoy your weekends in a resort atmosphere, at a home away from home amidst greenery, tranquility and various amenities.',
        pic:'https://a0.muscache.com/im/pictures/f15cc2bf-6877-4901-9d91-a63b318aed34.jpg?im_w=1200',
        price:15000,
        guest:6,
        bedroom:2,
        beds:4,
        bathroom:2,
        location:'Kerala'
    },
    {   
        id:65211214,
        name:'Amreena Farmhouse - Stay-Lunch-Dinner-Brkfst.',
        des:'PRICE IS PER PERSON PER NIGHT including breakfast lunch dinner with Veg and non veg food.  Amreena Farmhouse, the highest rated farmhouse on airbnb, is a beautiful space, just 2 to 2.5 hours away from Mumbai. Its in a place called Avalas which is 7 kms from Karjat and 3kms from Raddison hotel. ',
        pic:'https://a0.muscache.com/im/pictures/60dcd026-419d-4a06-a096-f5b676c8bda6.jpg?im_w=1200',
        price:6500,
        guest:4,
        bedroom:1,
        beds:3,
        bathroom:1,
        location:'Darjelling WestBengal'
    }
]
export default list;